using BizsolERPMain.Models;
using Elfie.Serialization;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Diagnostics;



namespace BizsolERPMain.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;
        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        public IActionResult Index(string AuthKey)
        {
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPMainDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test1\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.95.38.103;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.95.38.103;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test2;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test2\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           // AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.225,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBLoafIndiaUI_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.225,65446; initial catalog = BizsolERPMainDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.225,65446; initial catalog = BizsolERPDMSDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBLoafIndiaUI_Temp\",\"ERPMainDB_Name\":\"BizsolERPMainDB_LoafIndia\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_LoafIndia\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"79\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
           //AuthKey = "{\"ERPDBConStr\":\"Data Source=122.186.154.46,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBInframat_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPMainDB_Inframat_Test1; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPDMSDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBInframat_Test1\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Inframat_Test1\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_Inframat\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";

            ViewBag.AppBaseURL = _configuration["AppBaseURL"];
            ViewBag.AuthKey = AuthKey;
           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}
