using BizsolERPMain.Models;
using Elfie.Serialization;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using System.Text;



namespace BizsolERPMain.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;
        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Index(string AuthKey, [FromForm] string bizsolERPConnectionDetailsJson)
        {
            // If POST request with bizsolERPConnectionDetailsJson, use it as AuthKey
            if (!string.IsNullOrEmpty(bizsolERPConnectionDetailsJson))
            {
                AuthKey = bizsolERPConnectionDetailsJson;
            }
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=122.186.154.46,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizSolERPMainDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test1\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPMainDB_INFRAMAT_Test1; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test1\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT_Test1\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT;\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"138\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.95.38.103;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.95.38.103; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=122.186.154.46,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBInframat_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPMainDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPDMSDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBInframat_Test1\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Inframat_Test1\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_Inframat\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.246.196.247;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //   AuthKey = "{\"ERPDBConStr\":\"Data Source=26.246.196.247;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=45.248.120.221;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 45.248.120.221; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=122.186.154.46,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBInframat_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPMainDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPDMSDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBInframat_Test1\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Inframat_Test1\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_Inframat\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizsolERPTestMainDB_Inframat_Test1; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT_Test1; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test1\",\"ERPMainDB_Name\":\"BizsolERPTestMainDB_Inframat_Test1\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT_Test1\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPMainDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=26.246.196.247;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSalPapers_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPMainDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPDMSDB_SalPapers; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSalPapers_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SalPapers\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SalPapers\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"54\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=192.168.1.208;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPolytex_Temp;User ID=sa;pwd=biz@polytex;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPMainDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 192.168.1.208; initial catalog = BizSolERPDMSDB_Polytex; uid = sa; PWD = biz@polytex; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPolytex_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Polytex\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Polytex\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"115\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBBizDev;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBBizDev\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=103.47.151.151,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBHariomMain_Test;User ID=sa;pwd=hariom@biz@1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPMainDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 103.47.151.151,65446; initial catalog = BizsolERPDMSDB_Hariom; uid = sa; PWD = hariom@biz@1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBHariomMain_Test\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Hariom\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"261\",\"CompanyCode\":\"24\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.98,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPMainDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.98,65446; initial catalog = BizSolERPDMSDB_BizDev; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_BizDev\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_BizDev\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"145\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=220.158.165.225,65446;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBLoafIndiaUI_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 220.158.165.225,65446; initial catalog = BizsolERPMainDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 220.158.165.225,65446; initial catalog = BizsolERPDMSDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBLoafIndiaUI_Temp\",\"ERPMainDB_Name\":\"BizsolERPMainDB_LoafIndia\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_LoafIndia\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"79\",\"CompanyCode\":\"102\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=122.186.154.46,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBInframat_Test1;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPMainDB_Inframat_Test1; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 122.186.154.46,14332; initial catalog = BizsolERPDMSDB_Inframat; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBInframat_Test1\",\"ERPMainDB_Name\":\"BizsolERPMainDB_Inframat_Test1\",\"ERPDMSDB_Name\":\"BizsolERPDMSDB_Inframat\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\"}";


            //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Manoj_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPMainDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Manoj_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"103\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=137.97.228.170,14332;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBINFRAMAT_Test;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPMainDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 137.97.228.170,14332; initial catalog = BizSolERPDMSDB_INFRAMAT; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBINFRAMAT_Test\",\"ERPMainDB_Name\":\"BizSolERPMainDB_INFRAMAT\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_INFRAMAT\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"180\",\"CompanyCode\":\"104\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";

            //  AuthKey = "{\"ERPDBConStr\":\"Data Source=26.163.223.173;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBVimla_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.163.223.173; initial catalog = BizSolERPMainDB_VIMLA; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.163.223.173; initial catalog = BizSolERPDMSDB_VIMLA; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBVimla_Temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_VIMLA\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_VIMLA\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"204\",\"CompanyCode\":\"21\",\"CrystalReportBaseUrl\":\"https://web.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";

            //  AuthKey = "{\"ERPDBConStr\":\"Data Source=26.246.196.247;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBLoafIndiaUI_TempVijay;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.246.196.247; initial catalog = BizsolERPMainDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.246.196.247; initial catalog = BizSolERPDMSDB_LoafIndia; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBLoafIndiaUI_TempVijay\",\"ERPMainDB_Name\":\"BizsolERPMainDB_LoafIndia\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_LoafIndia\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"79\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://salpapers.bizsol.in/CRReports/Reports/Report.aspx?\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.127.52.5;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBGlobus_UI_TempShekhar;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.127.52.5; initial catalog = BizSolERPMainDB_Globus; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.127.52.5; initial catalog = BizSolERPDMSDB_Globus; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBGlobus_UI_TempShekhar\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Globus\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Globus\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\"}";

            // AuthKey = "{\"ERPDBConStr\":\"Data Source=26.228.46.4;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.228.46.4; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.228.46.4; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"126\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"4\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"131\",\"CompanyCode\":\"4\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes2022_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"126\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";

            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.52.187.217;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBASTPipes2022_Temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPMainDB_ASTPipes; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.52.187.217; initial catalog = BizSolERPDMSDB_ASTPIPES; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBASTPipes_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_ASTPipes\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_ASTPIPES\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"4\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";

            //59
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.164.1.186;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPPPLNew_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPMainDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPDMSDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPPPLNew_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_PPPL\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_PPPL\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"124\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"59\",\"WebERPLoginGodownName\":\"PPPL-JODHPUR\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.164.1.186;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPPPLNew;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPMainDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPDMSDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPPPLNew\",\"ERPMainDB_Name\":\"BizSolERPMainDB_PPPL\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_PPPL\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"249\",\"CompanyCode\":\"2\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"59\",\"WebERPLoginGodownName\":\"PPPL-JODHPUR\"}";
            //52
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=26.164.1.186;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPPPLNew_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPMainDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPDMSDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPPPLNew_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_PPPL\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_PPPL\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"124\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"52\",\"WebERPLoginGodownName\":\"PPPL-2 (AHM)\"}";
            //
            // AuthKey = "{\"ERPDBConStr\":\"Data Source=26.164.1.186;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBPPPLNew_temp;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPMainDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.164.1.186; initial catalog = BizSolERPDMSDB_PPPL; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBPPPLNew_temp\",\"ERPMainDB_Name\":\"BizSolERPMainDB_PPPL\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_PPPL\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"124\",\"CompanyCode\":\"100\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"52\",\"WebERPLoginGodownName\":\"PPPL-2 (AHM)\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.227.118.67\\\\NEW;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSNSINFRAMainTesting;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.227.118.67\\\\NEW; initial catalog = BizSolERPMainDB_SNSINFRATesting; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.227.118.67\\\\NEW; initial catalog = BizSolERPDMSDB_SNSINFRATesting; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSNSINFRAMainTesting\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SNSINFRATesting\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SNSINFRATesting\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"116\",\"CompanyCode\":\"2\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"52\",\"WebERPLoginGodownName\":\"PPPL-2 (AHM)\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.227.118.67\\\\\\\\NEW;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBSNSINFRASonipatTesting;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.227.118.67\\\\\\\\NEW; initial catalog = BizSolERPMainDB_SNSINFRATesting; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.227.118.67\\\\\\\\NEW; initial catalog = BizSolERPDMSDB_SNSINFRATesting; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBSNSINFRASonipatTesting\",\"ERPMainDB_Name\":\"BizSolERPMainDB_SNSINFRATesting\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_SNSINFRATesting\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"116\",\"CompanyCode\":\"2\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"52\",\"WebERPLoginGodownName\":\"PPPL-2 (AHM)\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.228.46.4;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBEnquiry;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.228.46.4; initial catalog = BizSolERPMainDB_Enquiry; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.228.46.4; initial catalog = BizSolERPDMSDB_Enquiry; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBEnquiry\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Enquiry\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Enquiry\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"98\",\"CompanyCode\":\"3\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";
            //AuthKey = "{\"ERPDBConStr\":\"Data Source=26.64.50.72;Connection Timeout=0;Persist Security Info=true;Initial Catalog=BizSolERPDBAllianz_TempAG;User ID=sa;pwd=biz1981;Packet Size=32000\",\"ERPMainDBConStr\":\"data source = 26.64.50.72; initial catalog = BizSolERPMainDB_Allianz; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDMSDBConStr\":\"data source = 26.64.50.72; initial catalog = BizSolERPDMSDB_Allianz; uid = sa; PWD = biz1981; Max Pool Size = 5000\",\"ERPDB_Name\":\"BizSolERPDBAllianz_TempAG\",\"ERPMainDB_Name\":\"BizSolERPMainDB_Allianz\",\"ERPDMSDB_Name\":\"BizSolERPDMSDB_Allianz\",\"AuthToken\":\"xyz\",\"UserMaster_Code\":\"400\",\"CompanyCode\":\"2\",\"CrystalReportBaseUrl\":\"https://globus.bizsol.in/CRReports/Reports/Report.aspx?\",\"WebERPLoginGodownMaster_Code\":\"0\",\"WebERPLoginGodownName\":\"\"}";


            AuthKey = EncryptAuthKeyProperties(AuthKey, "ERPDBConStr", "ERPMainDBConStr", "ERPDMSDBConStr");
            var req = HttpContext.Request;
            var derivedBaseUrl = $"{req.Scheme}://{req.Host}{req.PathBase}";
            ViewBag.AppBaseURL = derivedBaseUrl;
            ViewBag.AuthKey = AuthKey;


            return View();
            
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public string EncryptPasswordAsync(string password)
        {
            StringBuilder encryptedPassword = new StringBuilder();
            foreach (char c in password)
            {
                encryptedPassword.Append(Convert.ToChar(Convert.ToInt32(c) + 10));
            }
            return encryptedPassword.ToString();
        }

        
        public string EncryptForJson(string value)
        {
            if (string.IsNullOrEmpty(value))
                return value;

            string encrypted = EncryptPasswordAsync(value);
            byte[] bytes = Encoding.UTF8.GetBytes(encrypted);
            return Convert.ToBase64String(bytes);
        }

       
        
        public string EncryptAuthKeyProperties(string authKeyJson, params string[] propertiesToEncrypt)
        {
            if (string.IsNullOrEmpty(authKeyJson))
                return authKeyJson;

            try
            {
                JObject authKeyObj = JObject.Parse(authKeyJson);

                foreach (string propertyName in propertiesToEncrypt)
                {
                    if (authKeyObj.TryGetValue(propertyName, out JToken token) && token.Type == JTokenType.String)
                    {
                        string originalValue = token.ToString();
                        string encryptedValue = EncryptForJson(originalValue);
                        authKeyObj[propertyName] = encryptedValue;
                    }
                }

                return authKeyObj.ToString(Newtonsoft.Json.Formatting.None);
            }
            catch
            {
                return authKeyJson;
            }
        }

    }
}
