<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <BaseOutputPath>D:\Ruchi Data\BizSolWebProjects\BizsolERPMain\BizsolERPMain\bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Areas\PurchaseTransactions\Data\**" />
    <Compile Remove="Areas\PurchaseTransactions\Models\**" />
    <Compile Remove="wwwroot\lib\**" />
    <Content Remove="Areas\PurchaseTransactions\Data\**" />
    <Content Remove="Areas\PurchaseTransactions\Models\**" />
    <Content Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="Areas\PurchaseTransactions\Data\**" />
    <EmbeddedResource Remove="Areas\PurchaseTransactions\Models\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <None Remove="Areas\PurchaseTransactions\Data\**" />
    <None Remove="Areas\PurchaseTransactions\Models\**" />
    <None Remove="wwwroot\lib\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Script\GRNPayment.js" />
    <Content Remove="wwwroot\Script\GRNPaymentEntry.js" />
    <Content Remove="wwwroot\Script\GRNService.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bizsol.WebERP.UI.Shared\Bizsol.WebERP.UI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

</Project>

