<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\JSServices\GRNPaymentEntryService.js" />
    <Content Remove="wwwroot\js\JSServices\MachineMaintenanceService.js" />
    <Content Remove="wwwroot\js\JSServices\SizeFillterControlService.js" />
    <Content Remove="wwwroot\js\JSServices\VendorMasterService.js" />
    <Content Remove="wwwroot\js\JSServices\_GRNPaymentService.js" />
    <Content Remove="wwwroot\js\JSServices\_GRNService.js" />
    <Content Remove="wwwroot\js\JSServices\_ItemMasterService.js" />
  </ItemGroup>
  
  <!--<ItemGroup>
    <Compile Remove="wwwroot\lib\**" />
    <Content Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <None Remove="wwwroot\lib\**" />
  </ItemGroup>-->

  <ItemGroup>
    <Folder Include="JSServices\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
  </ItemGroup>

</Project>
