<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\**" />
    <Content Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <None Remove="wwwroot\lib\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\CRMTransactions\Data\" />
    <Folder Include="Areas\CRMTransactions\Models\" />
    <Folder Include="wwwroot\css\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bizsol.WebERP.UI.Shared\Bizsol.WebERP.UI.Shared.csproj" />
  </ItemGroup>

</Project>
